# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(email: "tester.#@fi.com", first_name: "Tester", last_name: "", city: "City#", state: "S#", password: "123456", password_confirmation: "123456")
User.create(email: "tester.1@fi.com", first_name: "Tester", last_name: "One", city: "City1", state: "S1", password: "123456", password_confirmation: "123456", admin: false)
User.create(email: "tester.2@fi.com", first_name: "Tester", last_name: "Two", city: "City2", state: "S2", password: "123456", password_confirmation: "123456", admin: false)
User.create(email: "tester.3@fi.com", first_name: "Tester", last_name: "Three", city: "City3", state: "S3", password: "123456", password_confirmation: "123456", admin: false)
User.create(email: "tester.4@fi.com", first_name: "Tester", last_name: "Four", city: "City4", state: "S4", password: "123456", password_confirmation: "123456", admin: false)
User.create(email: "tester.5@fi.com", first_name: "Tester", last_name: "Five", city: "City5", state: "S5", password: "123456", password_confirmation: "123456", admin: false)

# Interest.create(name: "")
Interest.create(name: "Learning")
Interest.create(name: "Traveling")
Interest.create(name: "Volunteering")
Interest.create(name: "Moving")
Interest.create(name: "Playing")
Interest.create(name: "Creating")

#Choice.create(user_id: , interest_id:)
Choice.create(user_id: 1, subactivity_id: 1)
Choice.create(user_id: 1, subactivity_id: 2)
Choice.create(user_id: 1, subactivity_id: 3)
Choice.create(user_id: 2, subactivity_id: 4)
Choice.create(user_id: 2, subactivity_id: 5)
Choice.create(user_id: 2, subactivity_id: 6)
Choice.create(user_id: 3, subactivity_id: 7)
Choice.create(user_id: 3, subactivity_id: 8)
Choice.create(user_id: 4, subactivity_id: 9)
Choice.create(user_id: 5, subactivity_id: 10)

# Activity.create(name: "", description: "-----I'm a description of an activity!!!-----", interest_id: #)
Activity.create(name: "a foreign language", description: "-----I'm a description of an activity!!!-----", interest_id: 1)
Activity.create(name: "how to dance", description: "-----I'm a description of an activity!!!-----", interest_id: 1)
Activity.create(name: "computer programming", description:"Coding camps are pretty expensive--let's see if we can get a group together to do FreeCodeCamp?", interest_id: 1)
Activity.create(name: "Europe", description: "-----I'm a description of an activity!!!-----", interest_id: 2)
Activity.create(name: "USA", description: "-----I'm a description of an activity!!!-----", interest_id: 2)
Activity.create(name: "South America", description: "-----I'm a description of an activity!!!-----", interest_id: 2)
Activity.create(name: "animals", description: "-----I'm a description of an activity!!!-----", interest_id: 3)
Activity.create(name: "veterans", description: "-----I'm a description of an activity!!!-----", interest_id: 3)
Activity.create(name: "the homeless", description: "-----I'm a description of an activity!!!-----", interest_id: 3)
Activity.create(name: "London", description: "-----I'm a description of an activity!!!-----", interest_id: 4)
Activity.create(name: "Austin", description: "-----I'm a description of an activity!!!-----", interest_id: 4)
Activity.create(name: "Canada", description: "-----I'm a description of an activity!!!-----", interest_id: 4)
Activity.create(name: "computer games", description: "-----I'm a description of an activity!!!-----", interest_id: 5)
Activity.create(name: "sports", description: "Play some sports with some fun people. Maybe join a Zog League together since signing up as a free agent sucks?", interest_id: 5)
Activity.create(name: "board/card games", description: "-----I'm a description of an activity!!!-----", interest_id: 5)
Activity.create(name: "websites", description: "-----I'm a description of an activity!!!-----", interest_id: 6)
Activity.create(name: "iPhone apps", description: "-----I'm a description of an activity!!!-----", interest_id: 6)
Activity.create(name: "woodwork", description: "-----I'm a description of an activity!!!-----", interest_id: 6)

# Subactivity.create(name: "", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: #)
Subactivity.create(name: "Spanish", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 1)
Subactivity.create(name: "French", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 1)
Subactivity.create(name: "salsa dancing", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 2)
Subactivity.create(name: "breakdancing", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 2)
Subactivity.create(name: "Ruby", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 3)
Subactivity.create(name: "JavaScript", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 3)
Subactivity.create(name: "skiing in Switzerland", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 4)
Subactivity.create(name: "backpacking in France", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 4)
Subactivity.create(name: "booze cruise", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 5)
Subactivity.create(name: "road trip", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 5)
Subactivity.create(name: "Machu Pichu", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 6)
Subactivity.create(name: "Mayan ruins", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 6)
Subactivity.create(name: "PETA fundraiser", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 7)
Subactivity.create(name: "Humane Society", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 7)
Subactivity.create(name: "Wounded Warrior Project", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 8)
Subactivity.create(name: "Gary Sinise Foundation", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 8)
Subactivity.create(name: "Ali Forney Center", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 9)
Subactivity.create(name: "Bowery Mission", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 9)
Subactivity.create(name: "for six months", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 10)
Subactivity.create(name: "indefinitely", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 10)
Subactivity.create(name: "for three months", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 11)
Subactivity.create(name: "indefinitely", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 11)
Subactivity.create(name: "for a year", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 12)
Subactivity.create(name: "indefinitely", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 12)
Subactivity.create(name: "Super Smash Bros", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 13)
Subactivity.create(name: "League of Legends", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 13)
Subactivity.create(name: "soccer", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 14)
Subactivity.create(name: "basketball", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 14)
Subactivity.create(name: "Settlers of Catan", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 15)
Subactivity.create(name: "Poker", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 15)
Subactivity.create(name: "social media", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 16)
Subactivity.create(name: "outdoor gear swapping", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 16)
Subactivity.create(name: "photo editors", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 17)
Subactivity.create(name: "games", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 17)
Subactivity.create(name: "sculptures", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 18)
Subactivity.create(name: "furniture", description: "-----I'm a description of a subactivity-----", commitment: 1, activity_id: 18)
